const withTranspileModules = require('next-transpile-modules')([
  'bail',
  'ccount',
  'character-entities',
  'comma-separated-tokens',
  'hast-to-hyperscript',
  'hast-util-from-parse5',
  'hast-util-is-element',
  'hast-util-parse-selector',
  'hast-util-raw',
  'hast-util-to-html',
  'hast-util-to-parse5',
  'hast-util-whitespace',
  'html-void-elements',
  'hastscript',
  'is-plain-obj',
  'markdown-table',
  'mdast-util-definitions',
  'mdast-util-find-and-replace',
  'mdast-util-gfm',
  'mdast-util-from-markdown',
  'mdast-util-to-hast',
  'mdast-util-to-markdown',
  'mdast-util-to-string',
  'micromark',
  'micromark-extension-gfm',
  'micromark-util-combine-extensions',
  'micromark-util-encode',
  'micromark-util-html-tag-name',
  'micromark-util-resolve-all',
  'micromark-util-symbol',
  'unified',
  'unist-builder',
  'unist-util-is',
  'unist-util-generated',
  'unist-util-position',
  'unist-util-visit',
  'parse-entities',
  'property-information',
  'rehype-raw',
  'rehype-stringify',
  'remark-gfm',
  'remark-parse',
  'remark-rehype',
  'space-separated-tokens',
  'stringify-entities',
  'trough',
  'unist-util-stringify-position',
  'vfile',
  'web-namespaces',
  'zwitch',
]);
// 'ERR_REQUIRE_ESM'対策 nextではcommonjsでコンパイルするらしく、esmodule形式の外部ライブラリをそのまま使用できない。
// 追いトランスパイルで動作させる
// module.exports = withTranspileModules();

module.exports = {
  output: 'export'
};
